package fields

import "testing"

// TestTagValues verifies that FIX protocol constant values comply with the official specification
func TestTagValues(t *testing.T) {
	// Define test cases: constant name → actual value → expected value
	testCases := []struct {
		name     string
		actual   int
		expected int
	}{
		{"TagAccount", TagAccount, 1},
		{"TagAdvId", TagAdvId, 2},
		{"TagAdvRefID", TagAdvRefID, 3},
		{"TagAdvSide", TagAdvSide, 4},
		{"TagAdvTransType", TagAdvTransType, 5},
		{"TagAvgPx", TagAvgPx, 6},
		{"TagBeginSeqNo", TagBeginSeqNo, 7},
		{"TagBeginString", TagBeginString, 8},
		{"TagBodyLength", TagBodyLength, 9},
		{"TagCheckSum", TagCheckSum, 10},
		{"TagClOrdID", TagClOrdID, 11},
		{"TagCommission", TagCommission, 12},
		{"TagCommType", TagCommType, 13},
		{"TagCumQty", TagCumQty, 14},
		{"TagCurrency", TagCurrency, 15},
		{"TagEndSeqNo", TagEndSeqNo, 16},
		{"TagExecID", TagExecID, 17},
		{"TagExecInst", TagExecInst, 18},
		{"TagExecRefID", TagExecRefID, 19},
		{"TagExecTransType", TagExecTransType, 20},
		{"TagHandlInst", TagHandlInst, 21},
		{"TagIDSource", TagIDSource, 22},
		{"TagIOIid", TagIOIid, 23},
		{"TagIOIOthSvc", TagIOIOthSvc, 24},
		{"TagIOIQltyInd", TagIOIQltyInd, 25},
		{"TagIOIRefID", TagIOIRefID, 26},
		{"TagIOIShares", TagIOIShares, 27},
		{"TagIOITransType", TagIOITransType, 28},
		{"TagLastCapacity", TagLastCapacity, 29},
		{"TagLastMkt", TagLastMkt, 30},
		{"TagLastPx", TagLastPx, 31},
		{"TagLastShares", TagLastShares, 32},
		{"TagLinesOfText", TagLinesOfText, 33},
		{"TagMsgSeqNum", TagMsgSeqNum, 34},
		{"TagMsgType", TagMsgType, 35},
		{"TagNewSeqNo", TagNewSeqNo, 36},
		{"TagOrderID", TagOrderID, 37},
		{"TagOrderQty", TagOrderQty, 38},
		{"TagOrdStatus", TagOrdStatus, 39},
		{"TagOrdType", TagOrdType, 40},
		{"TagOrigClOrdID", TagOrigClOrdID, 41},
		{"TagOrigTime", TagOrigTime, 42},
		{"TagPossDupFlag", TagPossDupFlag, 43},
		{"TagPrice", TagPrice, 44},
		{"TagRefSeqNum", TagRefSeqNum, 45},
		{"TagRelatdSym", TagRelatdSym, 46},
		{"TagRule80A", TagRule80A, 47},
		{"TagSecurityID", TagSecurityID, 48},
		{"TagSenderCompID", TagSenderCompID, 49},
		{"TagSenderSubID", TagSenderSubID, 50},
		{"TagSendingDate", TagSendingDate, 51},
		{"TagSendingTime", TagSendingTime, 52},
		{"TagShares", TagShares, 53},
		{"TagSide", TagSide, 54},
		{"TagSymbol", TagSymbol, 55},
		{"TagTargetCompID", TagTargetCompID, 56},
		{"TagTargetSubID", TagTargetSubID, 57},
		{"TagText", TagText, 58},
		{"TagTimeInForce", TagTimeInForce, 59},
		{"TagTransactTime", TagTransactTime, 60},
		{"TagUrgency", TagUrgency, 61},
		{"TagValidUntilTime", TagValidUntilTime, 62},
		{"TagSettlmntTyp", TagSettlmntTyp, 63},
		{"TagFutSettDate", TagFutSettDate, 64},
		{"TagSymbolSfx", TagSymbolSfx, 65},
		{"TagListID", TagListID, 66},
		{"TagListSeqNo", TagListSeqNo, 67},
		{"TagTotNoOrders", TagTotNoOrders, 68},
		{"TagListExecInst", TagListExecInst, 69},
		{"TagAllocID", TagAllocID, 70},
		{"TagAllocTransType", TagAllocTransType, 71},
		{"TagRefAllocID", TagRefAllocID, 72},
		{"TagNoOrders", TagNoOrders, 73},
		{"TagAvgPrxPrecision", TagAvgPrxPrecision, 74},
		{"TagTradeDate", TagTradeDate, 75},
		{"TagExecBroker", TagExecBroker, 76},
		{"TagOpenClose", TagOpenClose, 77},
		{"TagNoAllocs", TagNoAllocs, 78},
		{"TagAllocAccount", TagAllocAccount, 79},
		{"TagAllocShares", TagAllocShares, 80},
		{"TagProcessCode", TagProcessCode, 81},
		{"TagNoRpts", TagNoRpts, 82},
		{"TagRptSeq", TagRptSeq, 83},
		{"TagCxlQty", TagCxlQty, 84},
		{"TagNoDlvyInst", TagNoDlvyInst, 85},
		{"TagDlvyInst", TagDlvyInst, 86},
		{"TagAllocStatus", TagAllocStatus, 87},
		{"TagAllocRejCode", TagAllocRejCode, 88},
		{"TagSignature", TagSignature, 89},
		{"TagSecureDataLen", TagSecureDataLen, 90},
		{"TagSecureData", TagSecureData, 91},
		{"TagBrokerOfCredit", TagBrokerOfCredit, 92},
		{"TagSignatureLength", TagSignatureLength, 93},
		{"TagEmailType", TagEmailType, 94},
		{"TagRawDataLength", TagRawDataLength, 95},
		{"TagRawData", TagRawData, 96},
		{"TagPossResend", TagPossResend, 97},
		{"TagEncryptMethod", TagEncryptMethod, 98},
		{"TagStopPx", TagStopPx, 99},
		{"TagExDestination", TagExDestination, 100},

		{"TagCxlRejReason", TagCxlRejReason, 102},
		{"TagOrdRejReason", TagOrdRejReason, 103},
		{"TagIOIQualifier", TagIOIQualifier, 104},
		{"TagWaveNo", TagWaveNo, 105},
		{"TagIssuer", TagIssuer, 106},
		{"TagSecurityDesc", TagSecurityDesc, 107},
		{"TagHeartBtInt", TagHeartBtInt, 108},
		{"TagClientID", TagClientID, 109},
		{"TagMinQty", TagMinQty, 110},
		{"TagMaxFloor", TagMaxFloor, 111},
		{"TagTestReqID", TagTestReqID, 112},
		{"TagReportToExch", TagReportToExch, 113},
		{"TagLocateReqd", TagLocateReqd, 114},
		{"TagOnBehalfOfCompID", TagOnBehalfOfCompID, 115},
		{"TagOnBehalfOfSubID", TagOnBehalfOfSubID, 116},
		{"TagQuoteID", TagQuoteID, 117},
		{"TagNetMoney", TagNetMoney, 118},
		{"TagSettlCurrAmt", TagSettlCurrAmt, 119},
		{"TagSettlCurrency", TagSettlCurrency, 120},
		{"TagForexReq", TagForexReq, 121},
		{"TagOrigSendingTime", TagOrigSendingTime, 122},
		{"TagGapFillFlag", TagGapFillFlag, 123},
		{"TagNoExecs", TagNoExecs, 124},
		{"TagCxlType", TagCxlType, 125},
		{"TagExpireTime", TagExpireTime, 126},
		{"TagDKReason", TagDKReason, 127},
		{"TagDeliverToCompID", TagDeliverToCompID, 128},
		{"TagDeliverToSubID", TagDeliverToSubID, 129},
		{"TagIOINaturalFlag", TagIOINaturalFlag, 130},
		{"TagQuoteReqID", TagQuoteReqID, 131},
		{"TagBidPx", TagBidPx, 132},
		{"TagOfferPx", TagOfferPx, 133},
		{"TagBidSize", TagBidSize, 134},
		{"TagOfferSize", TagOfferSize, 135},
		{"TagNoMiscFees", TagNoMiscFees, 136},
		{"TagMiscFeeAmt", TagMiscFeeAmt, 137},
		{"TagMiscFeeCurr", TagMiscFeeCurr, 138},
		{"TagMiscFeeType", TagMiscFeeType, 139},
		{"TagPrevClosePx", TagPrevClosePx, 140},
		{"TagResetSeqNumFlag", TagResetSeqNumFlag, 141},
		{"TagSenderLocationID", TagSenderLocationID, 142},
		{"TagTargetLocationID", TagTargetLocationID, 143},
		{"TagOnBehalfOfLocationID", TagOnBehalfOfLocationID, 144},
		{"TagDeliverToLocationID", TagDeliverToLocationID, 145},
		{"TagNoRelatedSym", TagNoRelatedSym, 146},
		{"TagSubject", TagSubject, 147},
		{"TagHeadline", TagHeadline, 148},
		{"TagURLLink", TagURLLink, 149},
		{"TagExecType", TagExecType, 150},
		{"TagLeavesQty", TagLeavesQty, 151},
		{"TagCashOrderQty", TagCashOrderQty, 152},
		{"TagAllocAvgPx", TagAllocAvgPx, 153},
		{"TagAllocNetMoney", TagAllocNetMoney, 154},
		{"TagSettlCurrFxRate", TagSettlCurrFxRate, 155},
		{"TagSettlCurrFxRateCalc", TagSettlCurrFxRateCalc, 156},
		{"TagNumDaysInterest", TagNumDaysInterest, 157},
		{"TagAccruedInterestRate", TagAccruedInterestRate, 158},
		{"TagAccruedInterestAmt", TagAccruedInterestAmt, 159},
		{"TagSettlInstMode", TagSettlInstMode, 160},
		{"TagAllocText", TagAllocText, 161},
		{"TagSettlInstID", TagSettlInstID, 162},
		{"TagSettlInstTransType", TagSettlInstTransType, 163},
		{"TagEmailThreadID", TagEmailThreadID, 164},
		{"TagSettlInstSource", TagSettlInstSource, 165},
		{"TagSettlLocation", TagSettlLocation, 166},
		{"TagSecurityType", TagSecurityType, 167},
		{"TagEffectiveTime", TagEffectiveTime, 168},
		{"TagStandInstDbType", TagStandInstDbType, 169},
		{"TagStandInstDbName", TagStandInstDbName, 170},
		{"TagStandInstDbID", TagStandInstDbID, 171},
		{"TagSettlDeliveryType", TagSettlDeliveryType, 172},
		{"TagSettlDepositoryCode", TagSettlDepositoryCode, 173},
		{"TagSettlBrkrCode", TagSettlBrkrCode, 174},
		{"TagSettlInstCode", TagSettlInstCode, 175},
		{"TagSecuritySettlAgentName", TagSecuritySettlAgentName, 176},
		{"TagSecuritySettlAgentCode", TagSecuritySettlAgentCode, 177},
		{"TagSecuritySettlAgentAcctNum", TagSecuritySettlAgentAcctNum, 178},
		{"TagSecuritySettlAgentAcctName", TagSecuritySettlAgentAcctName, 179},
		{"TagSecuritySettlAgentContactName", TagSecuritySettlAgentContactName, 180},
		{"TagSecuritySettlAgentContactPhone", TagSecuritySettlAgentContactPhone, 181},
		{"TagCashSettlAgentName", TagCashSettlAgentName, 182},
		{"TagCashSettlAgentCode", TagCashSettlAgentCode, 183},
		{"TagCashSettlAgentAcctNum", TagCashSettlAgentAcctNum, 184},
		{"TagCashSettlAgentAcctName", TagCashSettlAgentAcctName, 185},
		{"TagCashSettlAgentContactName", TagCashSettlAgentContactName, 186},
		{"TagCashSettlAgentContactPhone", TagCashSettlAgentContactPhone, 187},
		{"TagBidSpotRate", TagBidSpotRate, 188},
		{"TagBidForwardPoints", TagBidForwardPoints, 189},
		{"TagOfferSpotRate", TagOfferSpotRate, 190},
		{"TagOfferForwardPoints", TagOfferForwardPoints, 191},
		{"TagOrderQty2", TagOrderQty2, 192},
		{"TagFutSettDate2", TagFutSettDate2, 193},
		{"TagLastSpotRate", TagLastSpotRate, 194},
		{"TagLastForwardPoints", TagLastForwardPoints, 195},
		{"TagAllocLinkID", TagAllocLinkID, 196},
		{"TagAllocLinkType", TagAllocLinkType, 197},
		{"TagSecondaryOrderID", TagSecondaryOrderID, 198},
		{"TagNoIOIQualifiers", TagNoIOIQualifiers, 199},
		{"TagMaturityMonthYear", TagMaturityMonthYear, 200},
		{"TagPutOrCall", TagPutOrCall, 201},
		{"TagStrikePrice", TagStrikePrice, 202},
		{"TagCoveredOrUncovered", TagCoveredOrUncovered, 203},
		{"TagCustomerOrFirm", TagCustomerOrFirm, 204},
		{"TagMaturityDay", TagMaturityDay, 205},
		{"TagOptAttribute", TagOptAttribute, 206},
		{"TagSecurityExchange", TagSecurityExchange, 207},
		{"TagNotifyBrokerOfCredit", TagNotifyBrokerOfCredit, 208},
		{"TagAllocHandlInst", TagAllocHandlInst, 209},
		{"TagMaxShow", TagMaxShow, 210},
		{"TagPegDifference", TagPegDifference, 211},
		{"TagXmlDataLen", TagXmlDataLen, 212},
		{"TagXmlData", TagXmlData, 213},
		{"TagSettlInstRefID", TagSettlInstRefID, 214},
		{"TagNoRoutingIDs", TagNoRoutingIDs, 215},
		{"TagRoutingType", TagRoutingType, 216},
		{"TagRoutingID", TagRoutingID, 217},
		{"TagSpreadToBenchmark", TagSpreadToBenchmark, 218},
		{"TagBenchmark", TagBenchmark, 219},

		{"TagCouponRate", TagCouponRate, 223},

		{"TagContractMultiplier", TagContractMultiplier, 231},

		{"TagMDReqID", TagMDReqID, 262},
		{"TagSubscriptionRequestType", TagSubscriptionRequestType, 263},
		{"TagMarketDepth", TagMarketDepth, 264},
		{"TagMDUpdateType", TagMDUpdateType, 265},
		{"TagAggregatedBook", TagAggregatedBook, 266},
		{"TagNoMDEntryTypes", TagNoMDEntryTypes, 267},
		{"TagNoMDEntries", TagNoMDEntries, 268},
		{"TagMDEntryType", TagMDEntryType, 269},
		{"TagMDEntryPx", TagMDEntryPx, 270},
		{"TagMDEntrySize", TagMDEntrySize, 271},
		{"TagMDEntryDate", TagMDEntryDate, 272},
		{"TagMDEntryTime", TagMDEntryTime, 273},
		{"TagTickDirection", TagTickDirection, 274},
		{"TagMDMkt", TagMDMkt, 275},
		{"TagQuoteCondition", TagQuoteCondition, 276},
		{"TagTradeCondition", TagTradeCondition, 277},
		{"TagMDEntryID", TagMDEntryID, 278},
		{"TagMDUpdateAction", TagMDUpdateAction, 279},
		{"TagMDEntryRefID", TagMDEntryRefID, 280},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			if tc.actual != tc.expected {
				t.Errorf("Constant %s has an incorrect value: actual %d, expected %d", tc.name, tc.actual, tc.expected)
			}
		})
	}
}
